# Generated by Django 4.2 on 2023-06-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Role',
            field=models.CharField(default='Assistant Teacher', max_length=100),
        ),
    ]
