# Generated by Django 4.2 on 2023-06-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_email_teacher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_authenticate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(choices=[('Senior Teacher', 'Senior Teacher'), ('Associate Teacher', 'Associate Teacher'), ('Assistant Teacher', 'Assistant Teacher'), ('Professor', 'Professor')], default='Assistant Teacher', max_length=100),
        ),
    ]
