# Generated by Django 4.2 on 2023-06-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_authenticate',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
    ]
